# Build tests of various combinations of configure options
# (pre-release tests)

name: Extended build tests
run-name: Extended build tests
on:
  push:
    branches:
      - release-test
jobs:
  build:
    runs-on: ubuntu-24.04
    steps:
      - uses: actions/checkout@v4
      - run: sudo apt-get update -qqq
      - run: sudo apt-get install -y pkg-config gcc liblzo2-dev libzstd-dev libblkid-dev uuid-dev zlib1g-dev libext2fs-dev e2fsprogs libudev-dev python3-sphinx libaio-dev liburing-dev attr ccache libgcrypt20
      - name: Run tests/build-tests.sh
        run: ./tests/build-tests.sh --ccache
